name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: aspithost/actions/.github/workflows/build-node.yml@v1
    permissions:
      contents: read
      pull-requests: write
    with:
      run-sonar: true
      test-command: npm run test:cov:ci
      generate-vitest-coverage-report: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  release:
    needs: build
    uses: aspithost/actions/.github/workflows/release-npm.yml@v1
    permissions:
      contents: write
      id-token: write
    with:
      package-path: '.'
      artifact-name: dist
